apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-analytics
  namespace: redirect-application
spec:
  storageClassName: managed-csi-premium
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 32Gi