apiVersion: batch/v1
kind: Job
metadata:
  name: urlshortener-service-migrate
  namespace: redirect-application
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: <acr>.azurecr.io/urlshortener-service:v1
          command: ["/app/migrate"]
          envFrom:
            - configMapRef: { name: urlshortener-service-config }
            - secretRef:    { name: urlshortener-service-secret }