apiVersion: v1
kind: Secret
metadata:
  name: urlshortener-db-credentials
  namespace: urlshortener
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASS: devpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-db-credentials
  namespace: urlshortener
type: Opaque
stringData:
  DB_USER: analyticsuser
  DB_PASS: analyticspassword