apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-analytics
  namespace: urlshortener
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-analytics
  namespace: urlshortener
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres-analytics
  template:
    metadata:
      labels:
        app: postgres-analytics
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: analytics
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: analytics-db-credentials, key: DB_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: analytics-db-credentials, key: DB_PASS }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "analyticsuser", "-d", "analytics"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "250m", memory: "256Mi" }
            limits:   { memory: "1Gi" }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgdata-analytics
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-analytics
  namespace: urlshortener
spec:
  selector:
    app: postgres-analytics
  ports:
    - port: 5432
      targetPort: postgres
