apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: urlshortener
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: web